#   port mappings
#
#   service         local -> host
#   ------------------------------
#   web           80    -> 9090

version: '3.3'
services:
  web:
    build:
      context: ./web
    ports:
      - '9090:80'
    restart: always
    stdin_open: true
    tty: true
    
